name: push_demo
description: A new Flutter application.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  firebase_core: ^2.11.0
  firebase_messaging: ^14.5.0
  flutter:
    sdk: flutter
  http: ^1.2.1
  logger: ^1.0.0
  push_notification:
    path: ../

dev_dependencies:
  surf_lint_rules: ^3.0.0

flutter:
  uses-material-design: true
